baseURL = "/"
languageCode = "en-us"
title = "Workshop"
theme = "hugo-theme-learn"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "green"